openapi: 3.0.3
info:
  title: Feedly - OpenAPI 3.0
  description: Test assignment for Aola Company
  version: 1.0.1
servers:
  - url: https://localhost:8000/api
tags:
  - name: feed
    description: All that is related to feed entries
paths:
  /feed:
    get:
      tags:
        - feed
      summary: Get list of feed entries
      operationId: getFeedEntriesList
      parameters:
        - name: user_id
          in: query
          description: Used for authentication. Provide some ID from SiteUser model
          required: true
          schema:
            type: integer
        - name: type
          in: query
          required: false
          description: |
            Filter by feed entry type. Entries with type 'advertisement' will be included
            regardless of this field
          schema:
            type: string
            enum:
              - article
              - achievement
              - advertisement
        - name: limit
          in: query
          required: false
          description: Limit the number of entries returned in response
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: Specifies offset that will be applied for entries
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeedEntry'
        '403':
          description: Authentication failed
components:
  schemas:
    FeedEntry:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          description: Title that will be shown to user
        activity_type:
          type: string
          description: Type of the entry
          example: article
          enum:
            - article
            - achievement
            - advertisement
        timestamp:
          type: string
          format: date-time