ACTIVITY_ARTICLE = 'article'
ACTIVITY_ACHIEVEMENT = 'achievement'
ACTIVITY_ADVERTISEMENT = 'advertisement'

ACTIVITY_TYPES = (
    ACTIVITY_ARTICLE,
    ACTIVITY_ADVERTISEMENT,
    ACTIVITY_ACHIEVEMENT
)
